<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OnlineStoreService"
     targetNamespace="http://xmlns.techlabs.local/oracle/apps"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.techlabs.local/oracle/apps"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="OnlineStoreService">
        <plnk:role name="OnlineStoreService">
            <plnk:portType name="tns:OnlineStoreService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.techlabs.local/oracle/apps" location="oramds:/apps/POApplication/WSDLs/OnlineStoreService.wsdl"/>
</wsdl:definitions>
