<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="OrdersService"
     targetNamespace="/techlabs/services/common/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="/techlabs/services/common/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="OrdersService">
        <plnk:role name="OrdersService">
            <plnk:portType name="tns:OrdersService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="/techlabs/services/common/" location="http://orasoa12.techlabs.local:7004/OrdersSDO/OrdersService?WSDL"/>
</wsdl:definitions>
