<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ShippingRulesService"
     targetNamespace="http://xmlns.oracle.com/ShippingRules/ShippingRulesService"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:tns="http://xmlns.oracle.com/ShippingRules/ShippingRulesService"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ShippingRules.ShippingRulesService1">
        <plnk:role name="IDecisionService">
            <plnk:portType name="tns:IDecisionService"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/ShippingRules/ShippingRulesService" location="ShippingRulesService.wsdl"/>
</wsdl:definitions>
