package techlabs.services.common.serviceinterface;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;

import techlabs.views.common.ItemsVOSDO;
import techlabs.views.common.OrdersVOSDO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 16 09:56:04 EDT 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/techlabs/services/common/", name="OrdersService",
    wsdlLocation="techlabs/services/common/serviceinterface/OrdersService.wsdl")
@SDODatabinding(schemaLocation="techlabs/services/common/serviceinterface/OrdersService.xsd")
public interface OrdersService {
    public static final String NAME = "{/techlabs/services/common/}OrdersService";

    @WebMethod(action="/techlabs/services/common/getItemsVO1", operationName="getItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="getItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="getItemsVO1Response")
    @WebResult(name="result")
    ItemsVOSDO getItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="itemId")
        BigDecimal itemId) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/createItemsVO1",
        operationName="createItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="createItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="createItemsVO1Response")
    @WebResult(name="result")
    ItemsVOSDO createItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="itemsVO1")
        ItemsVOSDO itemsVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/updateItemsVO1",
        operationName="updateItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="updateItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="updateItemsVO1Response")
    @WebResult(name="result")
    ItemsVOSDO updateItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="itemsVO1")
        ItemsVOSDO itemsVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/deleteItemsVO1",
        operationName="deleteItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="deleteItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="deleteItemsVO1Response")
    void deleteItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="itemsVO1")
        ItemsVOSDO itemsVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/mergeItemsVO1",
        operationName="mergeItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="mergeItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="mergeItemsVO1Response")
    @WebResult(name="result")
    ItemsVOSDO mergeItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="itemsVO1")
        ItemsVOSDO itemsVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/findItemsVO1", operationName="findItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="findItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="findItemsVO1Response")
    @WebResult(name="result")
    List<ItemsVOSDO> findItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/processItemsVO1",
        operationName="processItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processItemsVO1Response")
    @WebResult(name="result")
    List<ItemsVOSDO> processItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="itemsVO1")
        List<ItemsVOSDO> itemsVO1, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/processCSItemsVO1",
        operationName="processCSItemsVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processCSItemsVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processCSItemsVO1Response")
    @WebResult(name="result")
    ProcessData processCSItemsVO1(@WebParam(mode = WebParam.Mode.IN, name="processData")
        ProcessData processData, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/getOrdersVO1", operationName="getOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="getOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="getOrdersVO1Response")
    @WebResult(name="result")
    OrdersVOSDO getOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="ordId")
        BigDecimal ordId) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/createOrdersVO1",
        operationName="createOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="createOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="createOrdersVO1Response")
    @WebResult(name="result")
    OrdersVOSDO createOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="ordersVO1")
        OrdersVOSDO ordersVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/updateOrdersVO1",
        operationName="updateOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="updateOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="updateOrdersVO1Response")
    @WebResult(name="result")
    OrdersVOSDO updateOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="ordersVO1")
        OrdersVOSDO ordersVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/deleteOrdersVO1",
        operationName="deleteOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="deleteOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="deleteOrdersVO1Response")
    void deleteOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="ordersVO1")
        OrdersVOSDO ordersVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/mergeOrdersVO1",
        operationName="mergeOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="mergeOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="mergeOrdersVO1Response")
    @WebResult(name="result")
    OrdersVOSDO mergeOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="ordersVO1")
        OrdersVOSDO ordersVO1) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/findOrdersVO1",
        operationName="findOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="findOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="findOrdersVO1Response")
    @WebResult(name="result")
    List<OrdersVOSDO> findOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/processOrdersVO1",
        operationName="processOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processOrdersVO1Response")
    @WebResult(name="result")
    List<OrdersVOSDO> processOrdersVO1(@WebParam(mode = WebParam.Mode.IN,
            name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="ordersVO1")
        List<OrdersVOSDO> ordersVO1, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="/techlabs/services/common/processCSOrdersVO1",
        operationName="processCSOrdersVO1")
    @RequestWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processCSOrdersVO1")
    @ResponseWrapper(targetNamespace="/techlabs/services/common/types/",
        localName="processCSOrdersVO1Response")
    @WebResult(name="result")
    ProcessData processCSOrdersVO1(@WebParam(mode = WebParam.Mode.IN, name="processData")
        ProcessData processData, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;
}
