package techlabs.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;

import techlabs.common.OnlineStoreViewSDO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 22 13:43:13 EDT 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="http://xmlns.techlabs.local/oracle/apps",
    name="OnlineStoreService", wsdlLocation="techlabs/common/serviceinterface/OnlineStoreService.wsdl")
@SDODatabinding(schemaLocation="techlabs/common/serviceinterface/OnlineStoreService.xsd")
public interface OnlineStoreService {
    public static final String NAME = "{http://xmlns.techlabs.local/oracle/apps}OnlineStoreService";

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/getOnlineStoreView1",
        operationName="getOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="getOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="getOnlineStoreView1Response")
    @WebResult(name="result")
    OnlineStoreViewSDO getOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="prodId")
        String prodId) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/createOnlineStoreView1",
        operationName="createOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="createOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="createOnlineStoreView1Response")
    @WebResult(name="result")
    OnlineStoreViewSDO createOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="onlineStoreView1")
        OnlineStoreViewSDO onlineStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/updateOnlineStoreView1",
        operationName="updateOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="updateOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="updateOnlineStoreView1Response")
    @WebResult(name="result")
    OnlineStoreViewSDO updateOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="onlineStoreView1")
        OnlineStoreViewSDO onlineStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/deleteOnlineStoreView1",
        operationName="deleteOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="deleteOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="deleteOnlineStoreView1Response")
    void deleteOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN, name="onlineStoreView1")
        OnlineStoreViewSDO onlineStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/mergeOnlineStoreView1",
        operationName="mergeOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="mergeOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="mergeOnlineStoreView1Response")
    @WebResult(name="result")
    OnlineStoreViewSDO mergeOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="onlineStoreView1")
        OnlineStoreViewSDO onlineStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/findOnlineStoreView1",
        operationName="findOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="findOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="findOnlineStoreView1Response")
    @WebResult(name="result")
    List<OnlineStoreViewSDO> findOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/processOnlineStoreView1",
        operationName="processOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processOnlineStoreView1Response")
    @WebResult(name="result")
    List<OnlineStoreViewSDO> processOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="onlineStoreView1")
        List<OnlineStoreViewSDO> onlineStoreView1, @WebParam(mode = WebParam.Mode.IN,
            name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/processCSOnlineStoreView1",
        operationName="processCSOnlineStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processCSOnlineStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processCSOnlineStoreView1Response")
    @WebResult(name="result")
    ProcessData processCSOnlineStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="processData")
        ProcessData processData, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;
}
