package techlabs.server.serviceinterface;

import java.lang.reflect.Method;

import java.util.List;

import javax.ejb.Remote;
import javax.ejb.Stateless;

import javax.interceptor.Interceptors;

import oracle.jbo.common.Diagnostic;
import oracle.jbo.common.sdo.SDOHelper;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.server.svc.ServiceContextInterceptor;
import oracle.jbo.server.svc.ServiceImpl;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;

import techlabs.common.OnlineStoreViewSDO;
import techlabs.common.serviceinterface.OnlineStoreService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 22 13:43:13 EDT 2016
// ---------------------------------------------------------------------
@Stateless(name="techlabs.common.OnlineStoreServiceBean", mappedName="OnlineStoreServiceBean")
@Remote(OnlineStoreService.class)
@PortableWebService(targetNamespace="http://xmlns.techlabs.local/oracle/apps",
    serviceName="OnlineStoreService", portName="OnlineStoreServiceSoapHttpPort",
    endpointInterface="techlabs.common.serviceinterface.OnlineStoreService")
@Interceptors( { ServiceContextInterceptor.class })
public class OnlineStoreServiceImpl extends ServiceImpl implements OnlineStoreService {
    private static boolean _isInited = false;

    /**
     * This is the default constructor (do not remove).
     */
    public OnlineStoreServiceImpl() {
        init();
        setApplicationModuleDefName("techlabs.OnlineStoreAppModule");
        setConfigurationName("OnlineStoreService");
    }

    /**
     * Generated method. Do not modify. Do initialization in the constructor
     */
    protected void init() {
        if (_isInited) {
            return;
        }
        synchronized (OnlineStoreServiceImpl.class) {
            if (_isInited) {
                return;
            }
            try {
                SDOHelper.INSTANCE.defineSchema("techlabs/common/serviceinterface/", "OnlineStoreService.xsd");
                _isInited = true;
            } catch (Exception ex) {
                Diagnostic.printStackTrace(ex);
            }
        }
    }

    /**
     * getOnlineStoreView1: generated method. Do not modify.
     */
    public OnlineStoreViewSDO getOnlineStoreView1(String prodId) throws ServiceException {
        return (OnlineStoreViewSDO)get(new Object[] { prodId },
                                       "OnlineStoreView1",
                                       OnlineStoreViewSDO.class);
    }

    /**
     * createOnlineStoreView1: generated method. Do not modify.
     */
    public OnlineStoreViewSDO createOnlineStoreView1(OnlineStoreViewSDO onlineStoreView1) throws ServiceException {
        return (OnlineStoreViewSDO)create(onlineStoreView1,
                                          "OnlineStoreView1");
    }

    /**
     * updateOnlineStoreView1: generated method. Do not modify.
     */
    public OnlineStoreViewSDO updateOnlineStoreView1(OnlineStoreViewSDO onlineStoreView1) throws ServiceException {
        return (OnlineStoreViewSDO)update(onlineStoreView1,
                                          "OnlineStoreView1");
    }

    /**
     * deleteOnlineStoreView1: generated method. Do not modify.
     */
    public void deleteOnlineStoreView1(OnlineStoreViewSDO onlineStoreView1) throws ServiceException {
        delete(onlineStoreView1, "OnlineStoreView1");
    }

    /**
     * mergeOnlineStoreView1: generated method. Do not modify.
     */
    public OnlineStoreViewSDO mergeOnlineStoreView1(OnlineStoreViewSDO onlineStoreView1) throws ServiceException {
        return (OnlineStoreViewSDO)merge(onlineStoreView1, "OnlineStoreView1");
    }

    /**
     * findOnlineStoreView1: generated method. Do not modify.
     */
    public List<OnlineStoreViewSDO> findOnlineStoreView1(FindCriteria findCriteria,
                                                         FindControl findControl) throws ServiceException {
        return (List<OnlineStoreViewSDO>)find(findCriteria, findControl,
                                              "OnlineStoreView1",
                                              OnlineStoreViewSDO.class);
    }

    /**
     * processOnlineStoreView1: generated method. Do not modify.
     */
    public List<OnlineStoreViewSDO> processOnlineStoreView1(String changeOperation,
                                                            List<OnlineStoreViewSDO> onlineStoreView1,
                                                            ProcessControl processControl) throws ServiceException {
        return (List<OnlineStoreViewSDO>)process(changeOperation,
                                                 processControl,
                                                 onlineStoreView1,
                                                 "OnlineStoreView1");
    }

    /**
     * processCSOnlineStoreView1: generated method. Do not modify.
     */
    public ProcessData processCSOnlineStoreView1(ProcessData processData,
                                                 ProcessControl processControl) throws ServiceException {
        return processChangeSummary(processData, processControl, "OnlineStoreView1");
    }
}
