<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://ns.techlabs.com/POApplication/POProcessing/Fulfillment" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://xmlns.oracle.com/ns/order" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://ns.techlabs.com/POApplication/POProcessing/ApproveCCOrder" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 plnk xsd wsdl client ns0 xp20 bpws mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ApproveCCOrder.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Order" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Fulfillment.wsdl"/>
            <oracle-xsl-mapper:rootElement name="fulfillmentRequest" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE MAY 03 16:46:38 EDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:fulfillmentRequest>
      <ns1:customerId>
        <xsl:value-of select="/ns1:Order/ns1:customerId"/>
      </ns1:customerId>
      <ns1:orderId>
        <xsl:value-of select="/ns1:Order/ns1:orderId"/>
      </ns1:orderId>
      <xsl:if test="/ns1:Order/ns1:payMethod">
        <ns1:payMethod>
          <xsl:value-of select="/ns1:Order/ns1:payMethod"/>
        </ns1:payMethod>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:shipMethod">
        <ns1:shipMethod>
          <xsl:value-of select="/ns1:Order/ns1:shipMethod"/>
        </ns1:shipMethod>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:orderTotal">
        <ns1:orderTotal>
          <xsl:value-of select="/ns1:Order/ns1:orderTotal"/>
        </ns1:orderTotal>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:status">
        <ns1:status>
          <xsl:value-of select="/ns1:Order/ns1:status"/>
        </ns1:status>
      </xsl:if>
      <xsl:if test="/ns1:Order/ns1:creditCard">
        <ns1:creditCard>
          <ns1:cardNumber>
            <xsl:value-of select="/ns1:Order/ns1:creditCard/ns1:cardNumber"/>
          </ns1:cardNumber>
          <ns1:cardType>
            <xsl:value-of select="/ns1:Order/ns1:creditCard/ns1:cardType"/>
          </ns1:cardType>
        </ns1:creditCard>
      </xsl:if>
      <ns1:items>
        <xsl:if test="/ns1:Order/ns1:items/ns1:inStock">
          <ns1:inStock>
            <xsl:value-of select="/ns1:Order/ns1:items/ns1:inStock"/>
          </ns1:inStock>
        </xsl:if>
        <xsl:for-each select="/ns1:Order/ns1:items/ns1:item">
          <ns1:item>
            <ns1:prodId>
              <xsl:value-of select="ns1:prodId"/>
            </ns1:prodId>
            <ns1:prodName>
              <xsl:value-of select="ns1:prodName"/>
            </ns1:prodName>
            <xsl:if test="ns1:price">
              <ns1:price>
                <xsl:value-of select="ns1:price"/>
              </ns1:price>
            </xsl:if>
            <xsl:if test="ns1:qty">
              <ns1:qty>
                <xsl:value-of select="ns1:qty"/>
              </ns1:qty>
            </xsl:if>
            <xsl:if test="ns1:itemTotal">
              <ns1:itemTotal>
                <xsl:value-of select="ns1:itemTotal"/>
              </ns1:itemTotal>
            </xsl:if>
          </ns1:item>
        </xsl:for-each>
      </ns1:items>
    </ns1:fulfillmentRequest>
  </xsl:template>
</xsl:stylesheet>