<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="/techlabs/services/common/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns3="/techlabs/common/types/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:types="/techlabs/services/common/types/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:errors="http://xmlns.oracle.com/adf/svc/errors/" xmlns:ns0="/techlabs/views/common/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:client="http://ns.techlabs.com/POApplication/POProcessing/Fulfillment" xmlns:ns4="commonj.sdo/xml" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns5="http://xmlns.oracle.com/adf/svc/types/" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns6="commonj.sdo/java" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns2="http://xmlns.oracle.com/ns/order" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="commonj.sdo" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns3 plnk wsdl client ns2 xsd tns types soap errors ns0 ns4 ns5 ns6 ns1 bpws xp20 bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Fulfillment.wsdl"/>
            <oracle-xsl-mapper:rootElement name="fulfillmentRequest" namespace="http://xmlns.oracle.com/ns/order"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://orafmw11.techlabs.local:8001/OrdersSDO/OrdersService?WSDL"/>
            <oracle-xsl-mapper:rootElement name="ordersVOSDO" namespace="/techlabs/views/common/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE MAY 03 16:46:38 EDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:ordersVOSDO>
      <ns0:OrdId>
        <xsl:value-of select="/ns2:fulfillmentRequest/ns2:orderId"/>
      </ns0:OrdId>
      <ns0:CustId>
        <xsl:value-of select="/ns2:fulfillmentRequest/ns2:customerId"/>
      </ns0:CustId>
      <ns0:TotalPrice>
        <xsl:value-of select="/ns2:fulfillmentRequest/ns2:orderTotal"/>
      </ns0:TotalPrice>
      <ns0:DateOrdered>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </ns0:DateOrdered>
      <ns0:DateShipped>
        <xsl:text disable-output-escaping="no"/>
      </ns0:DateShipped>
      <ns0:Status>
        <xsl:value-of select="/ns2:fulfillmentRequest/ns2:status"/>
      </ns0:Status>
      <xsl:for-each select="/ns2:fulfillmentRequest/ns2:items/ns2:item">
        <ns0:ItemsVO>
          <ns0:ItemId>
            <xsl:value-of select="concat(../../ns2:orderId,position())"/>
          </ns0:ItemId>
          <ns0:OrdId>
            <xsl:value-of select="../../ns2:orderId"/>
          </ns0:OrdId>
          <ns0:ProdId>
            <xsl:value-of select="ns2:prodId"/>
          </ns0:ProdId>
          <xsl:if test="ns2:price">
            <ns0:Price>
              <xsl:value-of select="ns2:price"/>
            </ns0:Price>
          </xsl:if>
          <ns0:Quantity>
            <xsl:value-of select="ns2:qty"/>
          </ns0:Quantity>
        </ns0:ItemsVO>
      </xsl:for-each>
    </ns0:ordersVOSDO>
  </xsl:template>
</xsl:stylesheet>