package techlabs.common.serviceinterface;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;

import techlabs.common.InternalStoreViewSDO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 21 22:17:32 EDT 2016
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="http://xmlns.techlabs.local/oracle/apps",
    name="InternalStoreService", wsdlLocation="techlabs/common/serviceinterface/InternalStoreService.wsdl")
@SDODatabinding(schemaLocation="techlabs/common/serviceinterface/InternalStoreService.xsd")
public interface InternalStoreService {
    public static final String NAME = "{http://xmlns.techlabs.local/oracle/apps}InternalStoreService";

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/getInternalStoreView1",
        operationName="getInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="getInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="getInternalStoreView1Response")
    @WebResult(name="result")
    InternalStoreViewSDO getInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="prodId")
        String prodId) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/createInternalStoreView1",
        operationName="createInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="createInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="createInternalStoreView1Response")
    @WebResult(name="result")
    InternalStoreViewSDO createInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="internalStoreView1")
        InternalStoreViewSDO internalStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/updateInternalStoreView1",
        operationName="updateInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="updateInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="updateInternalStoreView1Response")
    @WebResult(name="result")
    InternalStoreViewSDO updateInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="internalStoreView1")
        InternalStoreViewSDO internalStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/deleteInternalStoreView1",
        operationName="deleteInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="deleteInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="deleteInternalStoreView1Response")
    void deleteInternalStoreView1(@WebParam(mode = WebParam.Mode.IN, name="internalStoreView1")
        InternalStoreViewSDO internalStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/mergeInternalStoreView1",
        operationName="mergeInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="mergeInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="mergeInternalStoreView1Response")
    @WebResult(name="result")
    InternalStoreViewSDO mergeInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="internalStoreView1")
        InternalStoreViewSDO internalStoreView1) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/findInternalStoreView1",
        operationName="findInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="findInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="findInternalStoreView1Response")
    @WebResult(name="result")
    List<InternalStoreViewSDO> findInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/processInternalStoreView1",
        operationName="processInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processInternalStoreView1Response")
    @WebResult(name="result")
    List<InternalStoreViewSDO> processInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="changeOperation")
        String changeOperation, @WebParam(mode = WebParam.Mode.IN, name="internalStoreView1")
        List<InternalStoreViewSDO> internalStoreView1, @WebParam(mode = WebParam.Mode.IN,
            name="processControl")
        ProcessControl processControl) throws ServiceException;

    @WebMethod(action="http://xmlns.techlabs.local/oracle/apps/processCSInternalStoreView1",
        operationName="processCSInternalStoreView1")
    @RequestWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processCSInternalStoreView1")
    @ResponseWrapper(targetNamespace="http://xmlns.techlabs.local/oracle/apps/types/",
        localName="processCSInternalStoreView1Response")
    @WebResult(name="result")
    ProcessData processCSInternalStoreView1(@WebParam(mode = WebParam.Mode.IN,
            name="processData")
        ProcessData processData, @WebParam(mode = WebParam.Mode.IN, name="processControl")
        ProcessControl processControl) throws ServiceException;
}
