<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidateCreditCard"
     targetNamespace="http://xmlns.oracle.com/POApplication/CreditCardValidation/ValidateCreditCard"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://techlabs.local/ns/CCAuthorizationService"
     xmlns:tns="http://xmlns.oracle.com/POApplication/CreditCardValidation/ValidateCreditCard"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://techlabs.local/ns/CCAuthorizationService"
                        schemaLocation="../Schemas/creditcheck.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="CreditCheckRequest" element="inp1:CreditCheckRequest"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="CreditCheckResponse" element="inp1:CreditCheckResponse"/>
    </wsdl:message>
    <wsdl:message name="faultMessage">
        <wsdl:part name="CreditCheckFault" element="inp1:CreditCheckFault"/>
    </wsdl:message>
    <wsdl:portType name="creditcardvalidation">
        <wsdl:operation name="validatecreditcard">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
            <wsdl:fault name="validateCCfault" message="tns:faultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
